service: local-shortner
plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.9
  timeout: 60

functions:
  creteShortUrl:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true
  redirectUrl:
    handler: handler.redirect
    events:
      - http:
          path: /{shortId}
          method: get